services:
  backend:
    # Zieht das fertige Image aus deiner GitHub Registry
    image: ghcr.io/brahbrudi-sketch/memepump-backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production

  frontend:
    # Zieht das fertige Image aus deiner GitHub Registry
    image: ghcr.io/brahbrudi-sketch/memepump-frontend:latest
    restart: always
    ports:
      - "80:80" # Nginx l√§uft intern auf Port 80
    depends_on:
      - backend